### ISSUE TITLE
Wifi Drivers wont compile!

### ISSUE THREAD

**Issue by krak3n77** [osmc/rtl8192eu-osmc#1]
Im trying to compile them for my debian 8 arm linux system,

detectingdragon77@orangepione:~$ uname -a
Linux orangepione 3.4.113-sun8i #18 SMP PREEMPT Thu Jun 15 02:16:06 CEST 2017 armv7l GNU/Linux

Here is the error:

detectingdragon77@orangepione:~/rtl8192eu-osmc/rtl8192eu$ sudo dkms install rtl8192eu/1.0

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
'make' all KVER=3.4.113-sun8i....(bad exit status: 2)
Error! Bad return status for module build on kernel: 3.4.113-sun8i (armv7l)
Consult /var/lib/dkms/rtl8192eu/1.0/build/make.log for more information.

**Comment by samnazarko** [comment]
We don't use DKMS in OSMC and I do not recommend doing so.
The error is telling you to check the build log, which you have not included.

We bundle this driver with our kernel (which we maintain downstream). You should build it and bundle it in tree. 

Beware of 05b460cf439296d178bd7bf0fce7704dd03f3663. You will want to adjust your KSRC (likely the problem) as it is currently configured relatively for the OSMC build system.

**Comment by samnazarko** [comment]
Closing this issue as not related to OSMC.
